//! Lightweight localization registry for high-visibility TUI strings.
//!
//! This intentionally covers UI chrome only. It does not change model prompts,
//! model output language, provider behavior, or media payload semantics.

use unicode_width::{UnicodeWidthChar, UnicodeWidthStr};

#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TextDirection {
    Ltr,
    Rtl,
}

#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LocaleCoverage {
    V076Core,
    PlannedQa,
}

#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LocaleSpec {
    pub tag: &'static str,
    pub display_name: &'static str,
    pub script: &'static str,
    pub direction: TextDirection,
    pub fallback: &'static str,
    pub coverage: LocaleCoverage,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Locale {
    ZhHans,
}

impl Locale {
    pub fn tag(self) -> &'static str {
        match self {
            Self::ZhHans => "zh-Hans",
        }
    }

    pub fn translation_target_name(self) -> &'static str {
        match self {
            Self::ZhHans => "简体中文",
        }
    }

    #[allow(dead_code)]
    pub fn spec(self) -> LocaleSpec {
        match self {
            Self::ZhHans => LocaleSpec {
                tag: "zh-Hans",
                display_name: "简体中文",
                script: "Hans",
                direction: TextDirection::Ltr,
                fallback: "zh-Hans",
                coverage: LocaleCoverage::V076Core,
            },
        }
    }

    #[allow(dead_code)]
    pub fn shipped() -> &'static [Self] {
        &[Self::ZhHans]
    }
}

#[allow(dead_code)]
pub const PLANNED_QA_LOCALES: &[LocaleSpec] = &[
    LocaleSpec {
        tag: "ar",
        display_name: "Arabic",
        script: "Arab",
        direction: TextDirection::Rtl,
        fallback: "en",
        coverage: LocaleCoverage::PlannedQa,
    },
    LocaleSpec {
        tag: "hi",
        display_name: "Hindi",
        script: "Deva",
        direction: TextDirection::Ltr,
        fallback: "en",
        coverage: LocaleCoverage::PlannedQa,
    },
    LocaleSpec {
        tag: "bn",
        display_name: "Bengali",
        script: "Beng",
        direction: TextDirection::Ltr,
        fallback: "en",
        coverage: LocaleCoverage::PlannedQa,
    },
    LocaleSpec {
        tag: "id",
        display_name: "Indonesian",
        script: "Latin",
        direction: TextDirection::Ltr,
        fallback: "en",
        coverage: LocaleCoverage::PlannedQa,
    },
    LocaleSpec {
        tag: "sw",
        display_name: "Swahili",
        script: "Latin",
        direction: TextDirection::Ltr,
        fallback: "en",
        coverage: LocaleCoverage::PlannedQa,
    },
    LocaleSpec {
        tag: "ha",
        display_name: "Hausa",
        script: "Latin",
        direction: TextDirection::Ltr,
        fallback: "en",
        coverage: LocaleCoverage::PlannedQa,
    },
    LocaleSpec {
        tag: "yo",
        display_name: "Yoruba",
        script: "Latin",
        direction: TextDirection::Ltr,
        fallback: "en",
        coverage: LocaleCoverage::PlannedQa,
    },
    LocaleSpec {
        tag: "fr",
        display_name: "French",
        script: "Latin",
        direction: TextDirection::Ltr,
        fallback: "en",
        coverage: LocaleCoverage::PlannedQa,
    },
    LocaleSpec {
        tag: "fil",
        display_name: "Filipino/Tagalog",
        script: "Latin",
        direction: TextDirection::Ltr,
        fallback: "en",
        coverage: LocaleCoverage::PlannedQa,
    },
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MessageId {
    ComposerPlaceholder,
    HistorySearchPlaceholder,
    HistorySearchTitle,
    HistoryHintMove,
    HistoryHintAccept,
    HistoryHintRestore,
    HistoryNoMatches,
    // StatusPicker — `/statusline` multi-select footer-item picker.
    StatusPickerTitle,
    StatusPickerInstruction,
    StatusPickerActionToggle,
    StatusPickerActionAll,
    StatusPickerActionNone,
    StatusPickerActionSave,
    StatusPickerActionCancel,
    ConfigTitle,
    ConfigModalTitle,
    ConfigSearchPlaceholder,
    ConfigNoSettings,
    ConfigNoMatchesPrefix,
    ConfigFilteredSettings,
    ConfigShowing,
    ConfigFooterDefault,
    ConfigFooterScrollable,
    ConfigFooterFiltered,
    ConfigSectionProvider,
    ConfigSectionModel,
    ConfigSectionPermissions,
    ConfigSectionNetwork,
    ConfigSectionDisplay,
    ConfigSectionComposer,
    ConfigSectionSidebar,
    ConfigSectionHistory,
    ConfigSectionMcp,
    ConfigSectionFleet,
    ConfigSectionExperimental,
    ConfigScopeSession,
    ConfigScopeSaved,
    ConfigEditCancelled,
    ConfigEditTitlePrefix,
    ConfigEditScopeLabel,
    ConfigEditCurrentLabel,
    ConfigEditHintLabel,
    ConfigEditNewLabel,
    ConfigEditFooter,
    ConfigRowEffective,
    ConfigDefaultValue,
    ConfigDefaultReasoning,
    ConfigUnavailable,
    HelpTitle,
    HelpFilterPlaceholder,
    HelpFilterPrefix,
    HelpNoMatches,
    HelpSlashCommands,
    HelpKeybindings,
    HelpFooterTypeFilter,
    HelpFooterMove,
    HelpFooterJump,
    HelpFooterClose,
    CmdAttachDescription,
    CmdAnchorDescription,
    CmdCacheDescription,
    CmdChangeDescription,
    CmdChangeHeader,
    CmdChangeTranslationQueued,
    CmdChangeTranslationUnavailable,
    CmdChangePreviousVersion,
    CmdBalanceDescription,
    CmdClearDescription,
    CmdCompactDescription,
    CmdPurgeDescription,
    CmdConfigDescription,
    CmdContextDescription,
    CmdCostDescription,
    CmdDiffDescription,
    CmdEditDescription,
    CmdExitDescription,
    CmdExportDescription,
    CmdFeedbackDescription,
    CmdHfDescription,
    CmdHelpDescription,
    CmdProfileDescription,
    CmdHomeDescription,
    CmdHooksDescription,
    CmdAgentDescription,
    CmdGoalDescription,
    CmdInitDescription,
    CmdJobsDescription,
    CmdLinksDescription,
    CmdLoadDescription,
    CmdLogoutDescription,
    CmdMcpDescription,
    CmdMemoryDescription,
    CmdPluginDescription,
    CmdPluginNoneFound,
    CmdPluginNotFound,
    CmdPluginListHeader,
    CmdPluginDetailDescription,
    CmdPluginDetailSchema,
    CmdPluginDetailApproval,
    CmdPluginDetailPath,
    CmdModeDescription,
    CmdModelDescription,
    CmdModelsDescription,
    CmdNetworkDescription,
    CmdNoteDescription,
    CmdThemeDescription,
    CmdProviderDescription,
    CmdQueueDescription,
    CmdQueueUsage,
    CmdQueueDraftHeader,
    CmdQueueNoMessages,
    CmdQueueListHeader,
    CmdQueueTip,
    CmdQueueAlreadyEditing,
    CmdQueueNotFound,
    CmdQueueEditingStatus,
    CmdQueueEditingMessage,
    CmdQueueDropped,
    CmdQueueAlreadyEmpty,
    CmdQueueCleared,
    CmdQueueMissingIndex,
    CmdQueueIndexPositive,
    CmdQueueIndexMin,
    CmdRelayDescription,
    CmdRenameDescription,
    CmdRestoreDescription,
    CmdRetryDescription,
    CmdReviewDescription,
    CmdRlmDescription,
    CmdSaveDescription,
    CmdForkDescription,
    CmdNewDescription,
    CmdSessionsDescription,
    CmdSettingsDescription,
    CmdSidebarDescription,
    CmdSkillDescription,
    CmdSkillsDescription,
    CmdSlopDescription,
    CmdStashDescription,
    CmdStatusDescription,
    CmdStatuslineDescription,
    CmdFleetDescription,
    CmdSubagentsDescription,
    CmdSwarmDescription,
    CmdSystemDescription,
    CmdTaskDescription,
    CmdTokensDescription,
    CmdTranslateDescription,
    CmdTranslateOff,
    CmdTranslateOn,
    TranslationInProgress,
    TranslationComplete,
    TranslationFailed,
    CmdTrustDescription,
    CmdLspDescription,
    CmdShareDescription,
    CmdWorkspaceDescription,
    CmdUndoDescription,
    CmdVerboseDescription,
    CmdCacheAdvice,
    CmdCacheFootnote,
    CmdCacheHeader,
    CmdCacheNoData,
    CmdCacheTotals,
    CmdCostReport,
    CmdTokensCacheBoth,
    CmdTokensCacheHitOnly,
    CmdTokensCacheMissOnly,
    CmdTokensContextUnknownWindow,
    CmdTokensContextWithWindow,
    CmdTokensNotReported,
    CmdTokensReport,
    FooterAgentSingular,
    FooterAgentsPlural,
    FooterPressCtrlCAgain,
    FooterWorking,
    FooterBalancePrefix,
    HelpSectionActions,
    HelpSectionClipboard,
    HelpSectionEditing,
    HelpSectionHelp,
    HelpSectionModes,
    HelpSectionNavigation,
    HelpSectionSessions,
    KbScrollTranscript,
    KbNavigateHistory,
    KbScrollTranscriptAlt,
    KbBrowseHistory,
    KbScrollPage,
    KbJumpTopBottom,
    KbJumpTopBottomEmpty,
    KbJumpToolBlocks,
    KbMoveCursor,
    KbJumpLineStartEnd,
    KbDeleteChar,
    KbClearDraft,
    KbStashDraft,
    KbSearchHistory,
    KbInsertNewline,
    KbSendDraft,
    KbCloseMenu,
    KbCancelOrExit,
    KbShellControls,
    KbExitEmpty,
    KbCommandPalette,
    KbCancelBackgroundShellJobs,
    KbFuzzyFilePicker,
    KbCompactInspector,
    KbLastMessagePager,
    KbSelectedDetails,
    KbToolDetailsPager,
    KbThinkingPager,
    KbLiveTranscript,
    KbBacktrackMessage,
    KbCompleteCycleModes,
    KbJumpPlanAgentYolo,
    KbAltJumpPlanAgentYolo,
    KbFocusSidebar,
    KbSessionPicker,
    KbPasteAttach,
    KbCopySelection,
    KbContextMenu,
    KbAttachPath,
    KbHelpOverlay,
    KbToggleHelp,
    KbToggleHelpSlash,
    HelpUsageLabel,
    HelpAliasesLabel,
    SettingsTitle,
    SettingsConfigFile,
    ClearConversation,
    ClearConversationBusy,
    ModelChanged,
    LinksTitle,
    LinksDashboard,
    LinksDocs,
    LinksTip,
    SubagentsFetching,
    HelpUnknownCommand,
    HomeDashboardTitle,
    HomeModel,
    HomeMode,
    HomeWorkspace,
    HomeHistory,
    HomeTokens,
    HomeQueued,
    HomeSubagents,
    HomeSkill,
    HomeQuickActions,
    HomeQuickLinks,
    HomeQuickSkills,
    HomeQuickConfig,
    HomeQuickSettings,
    HomeQuickModel,
    HomeQuickSubagents,
    HomeQuickTaskList,
    HomeQuickHelp,
    HomeModeTips,
    HomeAgentModeTip,
    HomeAgentModeReviewTip,
    HomeAgentModeYoloTip,
    HomeYoloModeTip,
    HomeYoloModeCaution,
    HomePlanModeTip,
    HomePlanModeChecklistTip,
    HomeGoalModeTip,
    // Onboarding screens — language picker.
    OnboardLanguageTitle,
    OnboardLanguageBlurb,
    OnboardLanguageFooter,
    // Onboarding screens — API key entry.
    OnboardApiKeyTitle,
    OnboardApiKeyStep1,
    OnboardApiKeyStep2,
    OnboardApiKeySavedHint,
    OnboardApiKeyFormatHint,
    OnboardApiKeyPlaceholder,
    OnboardApiKeyLabel,
    OnboardApiKeyFooter,
    // Onboarding screens — workspace trust prompt.
    OnboardTrustTitle,
    OnboardTrustQuestion,
    OnboardTrustLocationPrefix,
    OnboardTrustRiskHint,
    OnboardTrustEffectHint,
    OnboardTrustFooterPrefix,
    OnboardTrustFooterMiddle,
    OnboardTrustFooterSuffix,
    // Onboarding screens — final tips screen.
    OnboardTipsTitle,
    OnboardTipsLine1,
    OnboardTipsLine2,
    OnboardTipsLine3,
    OnboardTipsLine4,
    OnboardTipsFooterEnter,
    OnboardTipsFooterAction,
    // Context menu.
    CtxMenuTitle,
    CtxMenuCopySelection,
    CtxMenuCopySelectionDesc,
    CtxMenuOpenSelection,
    CtxMenuOpenSelectionDesc,
    CtxMenuClearSelection,
    CtxMenuOpenDetails,
    CtxMenuCopyMessage,
    CtxMenuCopyMessageDesc,
    CtxMenuOpenInEditor,
    CtxMenuOpenInEditorDesc,
    CtxMenuShowCell,
    CtxMenuShowCellDesc,
    CtxMenuHideCell,
    CtxMenuHideCellDesc,
    CtxMenuShowHidden,
    CtxMenuShowHiddenDesc,
    CtxMenuPaste,
    CtxMenuPasteDesc,
    CtxMenuCmdPalette,
    CtxMenuCmdPaletteDesc,
    CtxMenuContextInspector,
    CtxMenuContextInspectorDesc,
    CtxMenuHelp,
    CtxMenuHelpDesc,
    // Agent fanout card.
    FanoutCounts,

    // App mode picker (prompt, names, hints) and composer vim indicator.
    ModePickerPrompt,
    AppModeAgent,
    AppModeYolo,
    AppModePlan,
    AppModeAgentHint,
    AppModePlanHint,
    AppModeYoloHint,
    VimModeNormal,
    VimModeInsert,
    VimModeVisual,

    // Approval dialog — risk badges, category labels, field labels, options.
    ApprovalRiskReview,
    ApprovalRiskDestructive,
    ApprovalCategorySafe,
    ApprovalCategoryFileWrite,
    ApprovalCategoryShell,
    ApprovalCategoryNetwork,
    ApprovalCategoryMcpRead,
    ApprovalCategoryMcpAction,
    ApprovalCategoryUnknown,
    ApprovalFieldType,
    ApprovalFieldAbout,
    ApprovalFieldImpact,
    ApprovalFieldParams,
    ApprovalOptionApproveOnce,
    ApprovalOptionApproveAlways,
    ApprovalOptionDeny,
    ApprovalOptionAbortTurn,
    ApprovalBlockTitle,
    ApprovalControlsHint,
    ApprovalChooseHint,
    ApprovalChooseAction,
    ApprovalIntentLabel,
    ApprovalMoreLines,
    // Sandbox elevation dialog.
    ElevationTitleSandboxDenied,
    ElevationTitleRequired,
    ElevationFieldTool,
    ElevationFieldCmd,
    ElevationFieldReason,
    ElevationImpactHeader,
    ElevationImpactNetwork,
    ElevationImpactWrite,
    ElevationImpactFullAccess,
    ElevationPromptProceed,
    ElevationOptionNetwork,
    ElevationOptionWrite,
    ElevationOptionFullAccess,
    ElevationOptionAbort,
    ElevationOptionNetworkDesc,
    ElevationOptionWriteDesc,
    ElevationOptionFullAccessDesc,
    ElevationOptionAbortDesc,

    CtxInspTitle,
    CtxInspSessionContext,
    CtxInspSystemPrompt,
    CtxInspReferences,
    CtxInspRecentTools,
    CtxInspModel,
    CtxInspWorkspace,
    CtxInspSession,
    CtxInspContext,
    CtxInspTranscript,
    CtxInspWorkspaceStatus,
    CtxInspNotSampledYet,
    CtxInspOk,
    CtxInspHigh,
    CtxInspCritical,
    CtxInspIncluded,
    CtxInspAttached,
    CtxInspNotIncluded,
    CtxInspOutputCaptured,
    CtxInspNoOutputYet,
    CtxInspNoSystemPrompt,
    CtxInspNoReferences,
    CtxInspNoToolActivity,
    CtxInspVHint,
    CtxInspCells,
    CtxInspApiMessages,
    CtxInspActive,
    CtxInspCell,
    CtxInspMoreReferences,
    CtxInspStablePrefix,
    CtxInspVolatileWorkingSet,
    CtxInspFirstLine,
    CtxInspTotal,
    CtxInspTextPromptLayers,
    CtxInspSingleTextBlob,
    CtxInspBlocks,
    CtxInspBlock,
    CtxInspTokens,
    CtxInspLayers,
    CtxInspNone,
    CtxInspEmpty,
    CtxInspCacheFriendly,
    CtxInspChangesByTurn,
    CtxInspStablePrefixOnly,
    CtxInspCacheTip,
    // Tool family labels (card headers, sidebar, footer).
    ToolFamilyRead,
    ToolFamilyPatch,
    ToolFamilyRun,
    ToolFamilyFind,
    ToolFamilyDelegate,
    ToolFamilyFanout,
    ToolFamilyRlm,
    ToolFamilyVerify,
    ToolFamilyThink,
    ToolFamilyGeneric,
    // Voice commands (/voice, /voice-send, /voice-control)
    CmdVoiceDescription,
    CmdVoiceSendDescription,
    CmdVoiceControlDescription,
    VoiceEnabled,
    VoiceDisabled,
    VoiceSendEnabled,
    VoiceSendDisabled,
    VoiceControlEnabled,
    VoiceControlDisabled,
    VoiceErrNoAuth,
    VoiceErrNoRecorder,
    VoiceErrNetwork,
    VoiceErrEmptySend,
    VoiceErrTooShort,
    VoiceRecording,
    VoiceProcessing,
    VoiceTranscribed,
}

#[allow(dead_code)]
pub const ALL_MESSAGE_IDS: &[MessageId] = &[
    MessageId::ComposerPlaceholder,
    MessageId::HistorySearchPlaceholder,
    MessageId::HistorySearchTitle,
    MessageId::HistoryHintMove,
    MessageId::HistoryHintAccept,
    MessageId::HistoryHintRestore,
    MessageId::HistoryNoMatches,
    MessageId::StatusPickerTitle,
    MessageId::StatusPickerInstruction,
    MessageId::StatusPickerActionToggle,
    MessageId::StatusPickerActionAll,
    MessageId::StatusPickerActionNone,
    MessageId::StatusPickerActionSave,
    MessageId::StatusPickerActionCancel,
    MessageId::ConfigTitle,
    MessageId::ConfigModalTitle,
    MessageId::ConfigSearchPlaceholder,
    MessageId::ConfigNoSettings,
    MessageId::ConfigNoMatchesPrefix,
    MessageId::ConfigFilteredSettings,
    MessageId::ConfigShowing,
    MessageId::ConfigFooterDefault,
    MessageId::ConfigFooterScrollable,
    MessageId::ConfigFooterFiltered,
    MessageId::ConfigSectionProvider,
    MessageId::ConfigSectionModel,
    MessageId::ConfigSectionPermissions,
    MessageId::ConfigSectionNetwork,
    MessageId::ConfigSectionDisplay,
    MessageId::ConfigSectionComposer,
    MessageId::ConfigSectionSidebar,
    MessageId::ConfigSectionHistory,
    MessageId::ConfigSectionMcp,
    MessageId::ConfigSectionFleet,
    MessageId::ConfigSectionExperimental,
    MessageId::ConfigScopeSession,
    MessageId::ConfigScopeSaved,
    MessageId::ConfigEditCancelled,
    MessageId::ConfigEditTitlePrefix,
    MessageId::ConfigEditScopeLabel,
    MessageId::ConfigEditCurrentLabel,
    MessageId::ConfigEditHintLabel,
    MessageId::ConfigEditNewLabel,
    MessageId::ConfigEditFooter,
    MessageId::ConfigRowEffective,
    MessageId::ConfigDefaultValue,
    MessageId::ConfigDefaultReasoning,
    MessageId::ConfigUnavailable,
    MessageId::HelpTitle,
    MessageId::HelpFilterPlaceholder,
    MessageId::HelpFilterPrefix,
    MessageId::HelpNoMatches,
    MessageId::HelpSlashCommands,
    MessageId::HelpKeybindings,
    MessageId::HelpFooterTypeFilter,
    MessageId::HelpFooterMove,
    MessageId::HelpFooterJump,
    MessageId::HelpFooterClose,
    MessageId::CmdAnchorDescription,
    MessageId::CmdAttachDescription,
    MessageId::CmdBalanceDescription,
    MessageId::CmdCacheDescription,
    MessageId::CmdClearDescription,
    MessageId::CmdCompactDescription,
    MessageId::CmdPurgeDescription,
    MessageId::CmdConfigDescription,
    MessageId::CmdContextDescription,
    MessageId::CmdCostDescription,
    MessageId::CmdDiffDescription,
    MessageId::CmdEditDescription,
    MessageId::CmdExitDescription,
    MessageId::CmdExportDescription,
    MessageId::CmdFeedbackDescription,
    MessageId::CmdHfDescription,
    MessageId::CmdHelpDescription,
    MessageId::CmdProfileDescription,
    MessageId::CmdHomeDescription,
    MessageId::CmdHooksDescription,
    MessageId::CmdAgentDescription,
    MessageId::CmdInitDescription,
    MessageId::CmdJobsDescription,
    MessageId::CmdLinksDescription,
    MessageId::CmdLoadDescription,
    MessageId::CmdLogoutDescription,
    MessageId::CmdMcpDescription,
    MessageId::CmdPluginDescription,
    MessageId::CmdPluginNoneFound,
    MessageId::CmdPluginNotFound,
    MessageId::CmdPluginListHeader,
    MessageId::CmdPluginDetailDescription,
    MessageId::CmdPluginDetailSchema,
    MessageId::CmdPluginDetailApproval,
    MessageId::CmdPluginDetailPath,
    MessageId::CmdMemoryDescription,
    MessageId::CmdModeDescription,
    MessageId::CmdModelDescription,
    MessageId::CmdModelsDescription,
    MessageId::CmdNetworkDescription,
    MessageId::CmdNoteDescription,
    MessageId::CmdProviderDescription,
    MessageId::CmdQueueDescription,
    MessageId::CmdQueueUsage,
    MessageId::CmdQueueDraftHeader,
    MessageId::CmdQueueNoMessages,
    MessageId::CmdQueueListHeader,
    MessageId::CmdQueueTip,
    MessageId::CmdQueueAlreadyEditing,
    MessageId::CmdQueueNotFound,
    MessageId::CmdQueueEditingStatus,
    MessageId::CmdQueueEditingMessage,
    MessageId::CmdQueueDropped,
    MessageId::CmdQueueAlreadyEmpty,
    MessageId::CmdQueueCleared,
    MessageId::CmdQueueMissingIndex,
    MessageId::CmdQueueIndexPositive,
    MessageId::CmdQueueIndexMin,
    MessageId::CmdRelayDescription,
    MessageId::CmdRenameDescription,
    MessageId::CmdRestoreDescription,
    MessageId::CmdRetryDescription,
    MessageId::CmdReviewDescription,
    MessageId::CmdRlmDescription,
    MessageId::CmdSaveDescription,
    MessageId::CmdNewDescription,
    MessageId::CmdSessionsDescription,
    MessageId::CmdSettingsDescription,
    MessageId::CmdSidebarDescription,
    MessageId::CmdSkillDescription,
    MessageId::CmdSkillsDescription,
    MessageId::CmdSlopDescription,
    MessageId::CmdStashDescription,
    MessageId::CmdStatusDescription,
    MessageId::CmdStatuslineDescription,
    MessageId::CmdFleetDescription,
    MessageId::CmdSubagentsDescription,
    MessageId::CmdSwarmDescription,
    MessageId::CmdSystemDescription,
    MessageId::CmdTaskDescription,
    MessageId::CmdTokensDescription,
    MessageId::CmdTranslateDescription,
    MessageId::CmdTranslateOff,
    MessageId::CmdTranslateOn,
    MessageId::TranslationInProgress,
    MessageId::TranslationComplete,
    MessageId::TranslationFailed,
    MessageId::CmdTrustDescription,
    MessageId::CmdLspDescription,
    MessageId::CmdShareDescription,
    MessageId::CmdWorkspaceDescription,
    MessageId::CmdUndoDescription,
    MessageId::CmdVerboseDescription,
    MessageId::CmdCacheAdvice,
    MessageId::CmdCacheFootnote,
    MessageId::CmdCacheHeader,
    MessageId::CmdCacheNoData,
    MessageId::CmdCacheTotals,
    MessageId::CmdChangeDescription,
    MessageId::CmdChangeHeader,
    MessageId::CmdChangeTranslationQueued,
    MessageId::CmdChangeTranslationUnavailable,
    MessageId::CmdChangePreviousVersion,
    MessageId::CmdCostReport,
    MessageId::CmdTokensCacheBoth,
    MessageId::CmdTokensCacheHitOnly,
    MessageId::CmdTokensCacheMissOnly,
    MessageId::CmdTokensContextUnknownWindow,
    MessageId::CmdTokensContextWithWindow,
    MessageId::CmdTokensNotReported,
    MessageId::CmdTokensReport,
    MessageId::FooterAgentSingular,
    MessageId::FooterAgentsPlural,
    MessageId::FooterPressCtrlCAgain,
    MessageId::FooterWorking,
    MessageId::FooterBalancePrefix,
    MessageId::HelpSectionActions,
    MessageId::HelpSectionClipboard,
    MessageId::HelpSectionEditing,
    MessageId::HelpSectionHelp,
    MessageId::HelpSectionModes,
    MessageId::HelpSectionNavigation,
    MessageId::HelpSectionSessions,
    MessageId::KbScrollTranscript,
    MessageId::KbNavigateHistory,
    MessageId::KbScrollTranscriptAlt,
    MessageId::KbBrowseHistory,
    MessageId::KbScrollPage,
    MessageId::KbJumpTopBottom,
    MessageId::KbJumpTopBottomEmpty,
    MessageId::KbJumpToolBlocks,
    MessageId::KbMoveCursor,
    MessageId::KbJumpLineStartEnd,
    MessageId::KbDeleteChar,
    MessageId::KbClearDraft,
    MessageId::KbStashDraft,
    MessageId::KbSearchHistory,
    MessageId::KbInsertNewline,
    MessageId::KbSendDraft,
    MessageId::KbCloseMenu,
    MessageId::KbCancelOrExit,
    MessageId::KbShellControls,
    MessageId::KbExitEmpty,
    MessageId::KbCommandPalette,
    MessageId::KbCancelBackgroundShellJobs,
    MessageId::KbFuzzyFilePicker,
    MessageId::KbCompactInspector,
    MessageId::KbLastMessagePager,
    MessageId::KbSelectedDetails,
    MessageId::KbToolDetailsPager,
    MessageId::KbThinkingPager,
    MessageId::KbLiveTranscript,
    MessageId::KbBacktrackMessage,
    MessageId::KbCompleteCycleModes,
    MessageId::KbJumpPlanAgentYolo,
    MessageId::KbAltJumpPlanAgentYolo,
    MessageId::KbFocusSidebar,
    MessageId::KbSessionPicker,
    MessageId::KbPasteAttach,
    MessageId::KbCopySelection,
    MessageId::KbContextMenu,
    MessageId::KbAttachPath,
    MessageId::KbHelpOverlay,
    MessageId::KbToggleHelp,
    MessageId::KbToggleHelpSlash,
    MessageId::HelpUsageLabel,
    MessageId::HelpAliasesLabel,
    MessageId::SettingsTitle,
    MessageId::SettingsConfigFile,
    MessageId::ClearConversation,
    MessageId::ClearConversationBusy,
    MessageId::ModelChanged,
    MessageId::LinksTitle,
    MessageId::LinksDashboard,
    MessageId::LinksDocs,
    MessageId::LinksTip,
    MessageId::SubagentsFetching,
    MessageId::HelpUnknownCommand,
    MessageId::HomeDashboardTitle,
    MessageId::HomeModel,
    MessageId::HomeMode,
    MessageId::HomeWorkspace,
    MessageId::HomeHistory,
    MessageId::HomeTokens,
    MessageId::HomeQueued,
    MessageId::HomeSubagents,
    MessageId::HomeSkill,
    MessageId::HomeQuickActions,
    MessageId::HomeQuickLinks,
    MessageId::HomeQuickSkills,
    MessageId::HomeQuickConfig,
    MessageId::HomeQuickSettings,
    MessageId::HomeQuickModel,
    MessageId::HomeQuickSubagents,
    MessageId::HomeQuickTaskList,
    MessageId::HomeQuickHelp,
    MessageId::HomeModeTips,
    MessageId::HomeAgentModeTip,
    MessageId::HomeAgentModeReviewTip,
    MessageId::HomeAgentModeYoloTip,
    MessageId::HomeYoloModeTip,
    MessageId::HomeYoloModeCaution,
    MessageId::HomePlanModeTip,
    MessageId::HomePlanModeChecklistTip,
    MessageId::HomeGoalModeTip,
    MessageId::OnboardLanguageTitle,
    MessageId::OnboardLanguageBlurb,
    MessageId::OnboardLanguageFooter,
    MessageId::OnboardApiKeyTitle,
    MessageId::OnboardApiKeyStep1,
    MessageId::OnboardApiKeyStep2,
    MessageId::OnboardApiKeySavedHint,
    MessageId::OnboardApiKeyFormatHint,
    MessageId::OnboardApiKeyPlaceholder,
    MessageId::OnboardApiKeyLabel,
    MessageId::OnboardApiKeyFooter,
    MessageId::OnboardTrustTitle,
    MessageId::OnboardTrustQuestion,
    MessageId::OnboardTrustLocationPrefix,
    MessageId::OnboardTrustRiskHint,
    MessageId::OnboardTrustEffectHint,
    MessageId::OnboardTrustFooterPrefix,
    MessageId::OnboardTrustFooterMiddle,
    MessageId::OnboardTrustFooterSuffix,
    MessageId::OnboardTipsTitle,
    MessageId::OnboardTipsLine1,
    MessageId::OnboardTipsLine2,
    MessageId::OnboardTipsLine3,
    MessageId::OnboardTipsLine4,
    MessageId::OnboardTipsFooterEnter,
    MessageId::OnboardTipsFooterAction,
    // Context menu.
    MessageId::CtxMenuTitle,
    MessageId::CtxMenuCopySelection,
    MessageId::CtxMenuCopySelectionDesc,
    MessageId::CtxMenuOpenSelection,
    MessageId::CtxMenuOpenSelectionDesc,
    MessageId::CtxMenuClearSelection,
    MessageId::CtxMenuOpenDetails,
    MessageId::CtxMenuCopyMessage,
    MessageId::CtxMenuCopyMessageDesc,
    MessageId::CtxMenuOpenInEditor,
    MessageId::CtxMenuOpenInEditorDesc,
    MessageId::CtxMenuShowCell,
    MessageId::CtxMenuShowCellDesc,
    MessageId::CtxMenuHideCell,
    MessageId::CtxMenuHideCellDesc,
    MessageId::CtxMenuShowHidden,
    MessageId::CtxMenuShowHiddenDesc,
    MessageId::CtxMenuPaste,
    MessageId::CtxMenuPasteDesc,
    MessageId::CtxMenuCmdPalette,
    MessageId::CtxMenuCmdPaletteDesc,
    MessageId::CtxMenuContextInspector,
    MessageId::CtxMenuContextInspectorDesc,
    MessageId::CtxMenuHelp,
    MessageId::CtxMenuHelpDesc,
    MessageId::FanoutCounts,
    MessageId::ModePickerPrompt,
    MessageId::AppModeAgent,
    MessageId::AppModeYolo,
    MessageId::AppModePlan,
    MessageId::AppModeAgentHint,
    MessageId::AppModePlanHint,
    MessageId::AppModeYoloHint,
    MessageId::VimModeNormal,
    MessageId::VimModeInsert,
    MessageId::VimModeVisual,
    MessageId::ApprovalRiskReview,
    MessageId::ApprovalRiskDestructive,
    MessageId::ApprovalCategorySafe,
    MessageId::ApprovalCategoryFileWrite,
    MessageId::ApprovalCategoryShell,
    MessageId::ApprovalCategoryNetwork,
    MessageId::ApprovalCategoryMcpRead,
    MessageId::ApprovalCategoryMcpAction,
    MessageId::ApprovalCategoryUnknown,
    MessageId::ApprovalFieldType,
    MessageId::ApprovalFieldAbout,
    MessageId::ApprovalFieldImpact,
    MessageId::ApprovalFieldParams,
    MessageId::ApprovalOptionApproveOnce,
    MessageId::ApprovalOptionApproveAlways,
    MessageId::ApprovalOptionDeny,
    MessageId::ApprovalOptionAbortTurn,
    MessageId::ApprovalBlockTitle,
    MessageId::ApprovalControlsHint,
    MessageId::ApprovalChooseHint,
    MessageId::ApprovalChooseAction,
    MessageId::ApprovalIntentLabel,
    MessageId::ApprovalMoreLines,
    MessageId::ElevationTitleSandboxDenied,
    MessageId::ElevationTitleRequired,
    MessageId::ElevationFieldTool,
    MessageId::ElevationFieldCmd,
    MessageId::ElevationFieldReason,
    MessageId::ElevationImpactHeader,
    MessageId::ElevationImpactNetwork,
    MessageId::ElevationImpactWrite,
    MessageId::ElevationImpactFullAccess,
    MessageId::ElevationPromptProceed,
    MessageId::ElevationOptionNetwork,
    MessageId::ElevationOptionWrite,
    MessageId::ElevationOptionFullAccess,
    MessageId::ElevationOptionAbort,
    MessageId::ElevationOptionNetworkDesc,
    MessageId::ElevationOptionWriteDesc,
    MessageId::ElevationOptionFullAccessDesc,
    MessageId::ElevationOptionAbortDesc,
    MessageId::CtxInspTitle,
    MessageId::CtxInspSessionContext,
    MessageId::CtxInspSystemPrompt,
    MessageId::CtxInspReferences,
    MessageId::CtxInspRecentTools,
    MessageId::CtxInspModel,
    MessageId::CtxInspWorkspace,
    MessageId::CtxInspSession,
    MessageId::CtxInspContext,
    MessageId::CtxInspTranscript,
    MessageId::CtxInspWorkspaceStatus,
    MessageId::CtxInspNotSampledYet,
    MessageId::CtxInspOk,
    MessageId::CtxInspHigh,
    MessageId::CtxInspCritical,
    MessageId::CtxInspIncluded,
    MessageId::CtxInspAttached,
    MessageId::CtxInspNotIncluded,
    MessageId::CtxInspOutputCaptured,
    MessageId::CtxInspNoOutputYet,
    MessageId::CtxInspNoSystemPrompt,
    MessageId::CtxInspNoReferences,
    MessageId::CtxInspNoToolActivity,
    MessageId::CtxInspVHint,
    MessageId::CtxInspCells,
    MessageId::CtxInspApiMessages,
    MessageId::CtxInspActive,
    MessageId::CtxInspCell,
    MessageId::CtxInspMoreReferences,
    MessageId::CtxInspStablePrefix,
    MessageId::CtxInspVolatileWorkingSet,
    MessageId::CtxInspFirstLine,
    MessageId::CtxInspTotal,
    MessageId::CtxInspTextPromptLayers,
    MessageId::CtxInspSingleTextBlob,
    MessageId::CtxInspBlocks,
    MessageId::CtxInspBlock,
    MessageId::CtxInspTokens,
    MessageId::CtxInspLayers,
    MessageId::CtxInspNone,
    MessageId::CtxInspEmpty,
    MessageId::CtxInspCacheFriendly,
    MessageId::CtxInspChangesByTurn,
    MessageId::CtxInspStablePrefixOnly,
    MessageId::CtxInspCacheTip,
    MessageId::ToolFamilyRead,
    MessageId::ToolFamilyPatch,
    MessageId::ToolFamilyRun,
    MessageId::ToolFamilyFind,
    MessageId::ToolFamilyDelegate,
    MessageId::ToolFamilyFanout,
    MessageId::ToolFamilyRlm,
    MessageId::ToolFamilyVerify,
    MessageId::ToolFamilyThink,
    MessageId::ToolFamilyGeneric,
    MessageId::CmdVoiceDescription,
    MessageId::CmdVoiceSendDescription,
    MessageId::CmdVoiceControlDescription,
    MessageId::VoiceEnabled,
    MessageId::VoiceDisabled,
    MessageId::VoiceSendEnabled,
    MessageId::VoiceSendDisabled,
    MessageId::VoiceControlEnabled,
    MessageId::VoiceControlDisabled,
    MessageId::VoiceErrNoAuth,
    MessageId::VoiceErrNoRecorder,
    MessageId::VoiceErrNetwork,
    MessageId::VoiceErrEmptySend,
    MessageId::VoiceErrTooShort,
    MessageId::VoiceRecording,
    MessageId::VoiceProcessing,
    MessageId::VoiceTranscribed,
];

pub fn tr(locale: Locale, id: MessageId) -> &'static str {
    fallback_translation(translation(locale, id), id)
}

pub fn thinking_translation_placeholder(locale: Locale) -> &'static str {
    match locale {
        Locale::ZhHans => "正在思考，完成后翻译为简体中文...",
    }
}

pub fn thinking_translation_in_progress(locale: Locale) -> &'static str {
    match locale {
        Locale::ZhHans => "正在翻译思考内容...",
    }
}

pub fn thinking_translation_complete(locale: Locale) -> &'static str {
    match locale {
        Locale::ZhHans => "思考内容翻译完成",
    }
}

pub fn thinking_translation_failed(locale: Locale) -> &'static str {
    match locale {
        Locale::ZhHans => "思考内容翻译失败",
    }
}

pub fn hidden_translation_failed(locale: Locale) -> &'static str {
    match locale {
        Locale::ZhHans => "翻译失败，原文已隐藏。",
    }
}

#[allow(dead_code)]
pub fn missing_message_ids(locale: Locale) -> Vec<MessageId> {
    ALL_MESSAGE_IDS
        .iter()
        .copied()
        .filter(|id| translation(locale, *id).is_none())
        .collect()
}

pub fn normalize_configured_locale(input: &str) -> Option<&'static str> {
    let normalized = normalize_locale_input(input);
    if matches!(normalized.as_str(), "" | "auto" | "system") {
        return Some("auto");
    }
    parse_locale(&normalized).map(Locale::tag)
}

pub fn resolve_locale(setting: &str) -> Locale {
    resolve_locale_with_env(setting, |key| std::env::var(key).ok())
}

pub fn resolve_locale_with_env<F>(_setting: &str, _env: F) -> Locale
where
    F: Fn(&str) -> Option<String>,
{
    // 始终返回中文简体
    Locale::ZhHans
}

#[allow(dead_code)]
pub fn truncate_to_width(text: &str, max_width: usize) -> String {
    if max_width == 0 {
        return String::new();
    }
    if text.width() <= max_width {
        return text.to_string();
    }

    let ellipsis_width = '…'.width().unwrap_or(1);
    if max_width <= ellipsis_width {
        return "…".to_string();
    }

    let limit = max_width - ellipsis_width;
    let mut out = String::new();
    let mut width = 0usize;
    for ch in text.chars() {
        let ch_width = ch.width().unwrap_or(0);
        if width + ch_width > limit {
            break;
        }
        out.push(ch);
        width += ch_width;
    }
    out.push('…');
    out
}

fn normalize_locale_input(input: &str) -> String {
    input
        .split('.')
        .next()
        .unwrap_or(input)
        .split('@')
        .next()
        .unwrap_or(input)
        .trim()
        .replace('_', "-")
        .to_lowercase()
}

fn parse_locale(value: &str) -> Option<Locale> {
    if value.starts_with("zh") {
        return Some(Locale::ZhHans);
    }
    None
}

fn fallback_translation(candidate: Option<&'static str>, id: MessageId) -> &'static str {
    candidate.unwrap_or_else(|| chinese_simplified(id).unwrap_or("未知消息"))
}

fn translation(locale: Locale, id: MessageId) -> Option<&'static str> {
    match locale {
        Locale::ZhHans => chinese_simplified(id),
    }
}

fn chinese_simplified(id: MessageId) -> Option<&'static str> {
    Some(match id {
        MessageId::ComposerPlaceholder => "输入任务或使用 /",
        MessageId::HistorySearchPlaceholder => "搜索历史记录...",
        MessageId::HistorySearchTitle => "历史搜索",
        MessageId::HistoryHintMove => "上/下移动",
        MessageId::HistoryHintAccept => "回车确认",
        MessageId::HistoryHintRestore => "Esc 恢复",
        MessageId::HistoryNoMatches => "  无匹配",
        MessageId::StatusPickerTitle => "状态栏配置",
        MessageId::StatusPickerInstruction => "空格切换  全选  取消  回车保存",
        MessageId::StatusPickerActionToggle => "切换",
        MessageId::StatusPickerActionAll => "全选",
        MessageId::StatusPickerActionNone => "取消",
        MessageId::StatusPickerActionSave => "保存",
        MessageId::StatusPickerActionCancel => "退出",
        MessageId::ConfigTitle => "配置",
        MessageId::ConfigModalTitle => "配置编辑",
        MessageId::ConfigSearchPlaceholder => "搜索配置项...",
        MessageId::ConfigNoSettings => "无配置项",
        MessageId::ConfigNoMatchesPrefix => "无匹配: ",
        MessageId::ConfigFilteredSettings => "已过滤",
        MessageId::ConfigShowing => "显示",
        MessageId::ConfigFooterDefault => "↑↓ 导航  回车编辑  / 搜索  Esc 退出",
        MessageId::ConfigFooterScrollable => "↑↓ 导航  回车编辑  / 搜索  Esc 退出",
        MessageId::ConfigFooterFiltered => "↑↓ 导航  回车编辑  Esc 退出",
        MessageId::ConfigSectionProvider => "提供商",
        MessageId::ConfigSectionModel => "模型",
        MessageId::ConfigSectionPermissions => "权限",
        MessageId::ConfigSectionNetwork => "网络",
        MessageId::ConfigSectionDisplay => "显示",
        MessageId::ConfigSectionComposer => "编辑器",
        MessageId::ConfigSectionSidebar => "侧边栏",
        MessageId::ConfigSectionHistory => "历史",
        MessageId::ConfigSectionMcp => "MCP",
        MessageId::ConfigSectionFleet => "舰队",
        MessageId::ConfigSectionExperimental => "实验性",
        MessageId::ConfigScopeSession => "会话",
        MessageId::ConfigScopeSaved => "已保存",
        MessageId::ConfigEditCancelled => "已取消",
        MessageId::ConfigEditTitlePrefix => "编辑",
        MessageId::ConfigEditScopeLabel => "范围",
        MessageId::ConfigEditCurrentLabel => "当前值",
        MessageId::ConfigEditHintLabel => "提示",
        MessageId::ConfigEditNewLabel => "新值",
        MessageId::ConfigEditFooter => "回车确认  Esc 取消",
        MessageId::ConfigRowEffective => "生效值",
        MessageId::ConfigDefaultValue => "默认值",
        MessageId::ConfigDefaultReasoning => "推理",
        MessageId::ConfigUnavailable => "不可用",
        MessageId::HelpTitle => "帮助",
        MessageId::HelpFilterPlaceholder => "过滤...",
        MessageId::HelpFilterPrefix => "过滤",
        MessageId::HelpNoMatches => "无匹配",
        MessageId::HelpSlashCommands => "斜杠命令",
        MessageId::HelpKeybindings => "快捷键",
        MessageId::HelpFooterTypeFilter => "类型过滤",
        MessageId::HelpFooterMove => "移动",
        MessageId::HelpFooterJump => "跳转",
        MessageId::HelpFooterClose => "关闭",
        MessageId::CmdAttachDescription => "附加文件或目录",
        MessageId::CmdAnchorDescription => "锚点管理",
        MessageId::CmdCacheDescription => "缓存管理",
        MessageId::CmdChangeDescription => "更改模型或提供商",
        MessageId::CmdChangeHeader => "更改",
        MessageId::CmdChangeTranslationQueued => "翻译队列",
        MessageId::CmdChangeTranslationUnavailable => "翻译不可用",
        MessageId::CmdChangePreviousVersion => "先前版本",
        MessageId::CmdBalanceDescription => "余额查询",
        MessageId::CmdClearDescription => "清除对话",
        MessageId::CmdCompactDescription => "压缩上下文",
        MessageId::CmdPurgeDescription => "清除所有数据",
        MessageId::CmdConfigDescription => "配置管理",
        MessageId::CmdContextDescription => "上下文检查",
        MessageId::CmdCostDescription => "成本报告",
        MessageId::CmdDiffDescription => "查看差异",
        MessageId::CmdEditDescription => "编辑文件",
        MessageId::CmdExitDescription => "退出",
        MessageId::CmdExportDescription => "导出对话",
        MessageId::CmdFeedbackDescription => "反馈",
        MessageId::CmdHfDescription => "HuggingFace",
        MessageId::CmdHelpDescription => "帮助",
        MessageId::CmdProfileDescription => "配置文件",
        MessageId::CmdHomeDescription => "主页",
        MessageId::CmdHooksDescription => "钩子管理",
        MessageId::CmdAgentDescription => "代理模式",
        MessageId::CmdGoalDescription => "目标模式",
        MessageId::CmdInitDescription => "初始化项目",
        MessageId::CmdJobsDescription => "后台任务",
        MessageId::CmdLinksDescription => "链接",
        MessageId::CmdLoadDescription => "加载文件",
        MessageId::CmdLogoutDescription => "退出登录",
        MessageId::CmdMcpDescription => "MCP 管理",
        MessageId::CmdMemoryDescription => "记忆管理",
        MessageId::CmdPluginDescription => "插件管理",
        MessageId::CmdPluginNoneFound => "未找到插件",
        MessageId::CmdPluginNotFound => "插件未找到",
        MessageId::CmdPluginListHeader => "插件列表",
        MessageId::CmdPluginDetailDescription => "描述",
        MessageId::CmdPluginDetailSchema => "模式",
        MessageId::CmdPluginDetailApproval => "审批",
        MessageId::CmdPluginDetailPath => "路径",
        MessageId::CmdModeDescription => "切换模式",
        MessageId::CmdModelDescription => "切换模型",
        MessageId::CmdModelsDescription => "列出模型",
        MessageId::CmdNetworkDescription => "网络状态",
        MessageId::CmdNoteDescription => "笔记管理",
        MessageId::CmdThemeDescription => "主题管理",
        MessageId::CmdProviderDescription => "切换提供商",
        MessageId::CmdQueueDescription => "队列管理",
        MessageId::CmdQueueUsage => "用法",
        MessageId::CmdQueueDraftHeader => "草稿",
        MessageId::CmdQueueNoMessages => "无消息",
        MessageId::CmdQueueListHeader => "消息列表",
        MessageId::CmdQueueTip => "提示",
        MessageId::CmdQueueAlreadyEditing => "已在编辑",
        MessageId::CmdQueueNotFound => "未找到",
        MessageId::CmdQueueEditingStatus => "编辑状态",
        MessageId::CmdQueueEditingMessage => "编辑消息",
        MessageId::CmdQueueDropped => "已丢弃",
        MessageId::CmdQueueAlreadyEmpty => "已为空",
        MessageId::CmdQueueCleared => "已清空",
        MessageId::CmdQueueMissingIndex => "缺少索引",
        MessageId::CmdQueueIndexPositive => "索引为正",
        MessageId::CmdQueueIndexMin => "最小索引",
        MessageId::CmdRelayDescription => "中继管理",
        MessageId::CmdRenameDescription => "重命名",
        MessageId::CmdRestoreDescription => "恢复",
        MessageId::CmdRetryDescription => "重试",
        MessageId::CmdReviewDescription => "审查",
        MessageId::CmdRlmDescription => "RLM",
        MessageId::CmdSaveDescription => "保存",
        MessageId::CmdForkDescription => "分叉",
        MessageId::CmdNewDescription => "新建",
        MessageId::CmdSessionsDescription => "会话管理",
        MessageId::CmdSettingsDescription => "设置",
        MessageId::CmdSidebarDescription => "侧边栏",
        MessageId::CmdSkillDescription => "技能",
        MessageId::CmdSkillsDescription => "技能列表",
        MessageId::CmdSlopDescription => "Slop",
        MessageId::CmdStashDescription => "暂存",
        MessageId::CmdStatusDescription => "状态",
        MessageId::CmdStatuslineDescription => "状态栏",
        MessageId::CmdFleetDescription => "舰队管理",
        MessageId::CmdSubagentsDescription => "子代理",
        MessageId::CmdSwarmDescription => "集群",
        MessageId::CmdSystemDescription => "系统信息",
        MessageId::CmdTaskDescription => "任务管理",
        MessageId::CmdTokensDescription => "Token 统计",
        MessageId::CmdTranslateDescription => "翻译",
        MessageId::CmdTranslateOff => "关闭翻译",
        MessageId::CmdTranslateOn => "开启翻译",
        MessageId::TranslationInProgress => "翻译中...",
        MessageId::TranslationComplete => "翻译完成",
        MessageId::TranslationFailed => "翻译失败",
        MessageId::CmdTrustDescription => "信任管理",
        MessageId::CmdLspDescription => "LSP",
        MessageId::CmdShareDescription => "分享",
        MessageId::CmdWorkspaceDescription => "工作区",
        MessageId::CmdUndoDescription => "撤销",
        MessageId::CmdVerboseDescription => "详细模式",
        MessageId::CmdCacheAdvice => "建议",
        MessageId::CmdCacheFootnote => "注释",
        MessageId::CmdCacheHeader => "缓存",
        MessageId::CmdCacheNoData => "无数据",
        MessageId::CmdCacheTotals => "总计",
        MessageId::CmdCostReport => "成本报告",
        MessageId::CmdTokensCacheBoth => "缓存命中/未命中",
        MessageId::CmdTokensCacheHitOnly => "仅缓存命中",
        MessageId::CmdTokensCacheMissOnly => "仅缓存未命中",
        MessageId::CmdTokensContextUnknownWindow => "未知窗口",
        MessageId::CmdTokensContextWithWindow => "带窗口",
        MessageId::CmdTokensNotReported => "未报告",
        MessageId::CmdTokensReport => "报告",
        MessageId::FooterAgentSingular => "代理",
        MessageId::FooterAgentsPlural => "代理",
        MessageId::FooterPressCtrlCAgain => "再按 Ctrl+C 退出",
        MessageId::FooterWorking => "工作中",
        MessageId::FooterBalancePrefix => "余额",
        MessageId::HelpSectionActions => "操作",
        MessageId::HelpSectionClipboard => "剪贴板",
        MessageId::HelpSectionEditing => "编辑",
        MessageId::HelpSectionHelp => "帮助",
        MessageId::HelpSectionModes => "模式",
        MessageId::HelpSectionNavigation => "导航",
        MessageId::HelpSectionSessions => "会话",
        MessageId::KbScrollTranscript => "滚动",
        MessageId::KbNavigateHistory => "历史导航",
        MessageId::KbScrollTranscriptAlt => "滚动",
        MessageId::KbBrowseHistory => "浏览历史",
        MessageId::KbScrollPage => "翻页",
        MessageId::KbJumpTopBottom => "跳转首尾",
        MessageId::KbJumpTopBottomEmpty => "跳转首尾",
        MessageId::KbJumpToolBlocks => "跳转工具块",
        MessageId::KbMoveCursor => "移动光标",
        MessageId::KbJumpLineStartEnd => "跳转行首尾",
        MessageId::KbDeleteChar => "删除字符",
        MessageId::KbClearDraft => "清除草稿",
        MessageId::KbStashDraft => "暂存草稿",
        MessageId::KbSearchHistory => "搜索历史",
        MessageId::KbInsertNewline => "插入换行",
        MessageId::KbSendDraft => "发送草稿",
        MessageId::KbCloseMenu => "关闭菜单",
        MessageId::KbCancelOrExit => "取消/退出",
        MessageId::KbShellControls => "Shell 控制",
        MessageId::KbExitEmpty => "退出空行",
        MessageId::KbCommandPalette => "命令面板",
        MessageId::KbCancelBackgroundShellJobs => "取消后台任务",
        MessageId::KbFuzzyFilePicker => "文件选择器",
        MessageId::KbCompactInspector => "紧凑检查器",
        MessageId::KbLastMessagePager => "最后消息分页",
        MessageId::KbSelectedDetails => "选中详情",
        MessageId::KbToolDetailsPager => "工具详情分页",
        MessageId::KbThinkingPager => "思考分页",
        MessageId::KbLiveTranscript => "实时转录",
        MessageId::KbBacktrackMessage => "回溯消息",
        MessageId::KbCompleteCycleModes => "完成循环模式",
        MessageId::KbJumpPlanAgentYolo => "跳转模式",
        MessageId::KbAltJumpPlanAgentYolo => "跳转模式",
        MessageId::KbFocusSidebar => "聚焦侧边栏",
        MessageId::KbSessionPicker => "会话选择器",
        MessageId::KbPasteAttach => "粘贴附件",
        MessageId::KbCopySelection => "复制选择",
        MessageId::KbContextMenu => "上下文菜单",
        MessageId::KbAttachPath => "附加路径",
        MessageId::KbHelpOverlay => "帮助覆盖",
        MessageId::KbToggleHelp => "切换帮助",
        MessageId::KbToggleHelpSlash => "切换帮助",
        MessageId::HelpUsageLabel => "用法",
        MessageId::HelpAliasesLabel => "别名",
        MessageId::SettingsTitle => "设置",
        MessageId::SettingsConfigFile => "配置文件",
        MessageId::ClearConversation => "清除对话",
        MessageId::ClearConversationBusy => "清除对话中",
        MessageId::ModelChanged => "模型已更改",
        MessageId::LinksTitle => "链接",
        MessageId::LinksDashboard => "仪表板",
        MessageId::LinksDocs => "文档",
        MessageId::LinksTip => "提示",
        MessageId::SubagentsFetching => "获取子代理中...",
        MessageId::HelpUnknownCommand => "未知命令",
        MessageId::HomeDashboardTitle => "仪表板",
        MessageId::HomeModel => "模型",
        MessageId::HomeMode => "模式",
        MessageId::HomeWorkspace => "工作区",
        MessageId::HomeHistory => "历史",
        MessageId::HomeTokens => "Token",
        MessageId::HomeQueued => "队列",
        MessageId::HomeSubagents => "子代理",
        MessageId::HomeSkill => "技能",
        MessageId::HomeQuickActions => "快速操作",
        MessageId::HomeQuickLinks => "快速链接",
        MessageId::HomeQuickSkills => "快速技能",
        MessageId::HomeQuickConfig => "快速配置",
        MessageId::HomeQuickSettings => "快速设置",
        MessageId::HomeQuickModel => "快速模型",
        MessageId::HomeQuickSubagents => "快速子代理",
        MessageId::HomeQuickTaskList => "快速任务",
        MessageId::HomeQuickHelp => "快速帮助",
        MessageId::HomeModeTips => "模式提示",
        MessageId::HomeAgentModeTip => "代理模式提示",
        MessageId::HomeAgentModeReviewTip => "代理审查提示",
        MessageId::HomeAgentModeYoloTip => "代理 Yolo 提示",
        MessageId::HomeYoloModeTip => "Yolo 模式提示",
        MessageId::HomeYoloModeCaution => "Yolo 模式警告",
        MessageId::HomePlanModeTip => "计划模式提示",
        MessageId::HomePlanModeChecklistTip => "计划清单提示",
        MessageId::HomeGoalModeTip => "目标模式提示",
        MessageId::OnboardLanguageTitle => "选择语言",
        MessageId::OnboardLanguageBlurb => "选择界面语言",
        MessageId::OnboardLanguageFooter => "按回车确认",
        MessageId::OnboardApiKeyTitle => "API 密钥",
        MessageId::OnboardApiKeyStep1 => "步骤 1",
        MessageId::OnboardApiKeyStep2 => "步骤 2",
        MessageId::OnboardApiKeySavedHint => "已保存",
        MessageId::OnboardApiKeyFormatHint => "格式提示",
        MessageId::OnboardApiKeyPlaceholder => "输入 API 密钥",
        MessageId::OnboardApiKeyLabel => "API 密钥",
        MessageId::OnboardApiKeyFooter => "按回车确认",
        MessageId::OnboardTrustTitle => "工作区信任",
        MessageId::OnboardTrustQuestion => "信任此工作区？",
        MessageId::OnboardTrustLocationPrefix => "位置",
        MessageId::OnboardTrustRiskHint => "风险提示",
        MessageId::OnboardTrustEffectHint => "效果提示",
        MessageId::OnboardTrustFooterPrefix => "前缀",
        MessageId::OnboardTrustFooterMiddle => "中间",
        MessageId::OnboardTrustFooterSuffix => "后缀",
        MessageId::OnboardTipsTitle => "提示",
        MessageId::OnboardTipsLine1 => "提示 1",
        MessageId::OnboardTipsLine2 => "提示 2",
        MessageId::OnboardTipsLine3 => "提示 3",
        MessageId::OnboardTipsLine4 => "提示 4",
        MessageId::OnboardTipsFooterEnter => "按回车继续",
        MessageId::OnboardTipsFooterAction => "操作",
        MessageId::CtxMenuTitle => "上下文菜单",
        MessageId::CtxMenuCopySelection => "复制选择",
        MessageId::CtxMenuCopySelectionDesc => "复制选择内容",
        MessageId::CtxMenuOpenSelection => "打开选择",
        MessageId::CtxMenuOpenSelectionDesc => "打开选择内容",
        MessageId::CtxMenuClearSelection => "清除选择",
        MessageId::CtxMenuOpenDetails => "打开详情",
        MessageId::CtxMenuCopyMessage => "复制消息",
        MessageId::CtxMenuCopyMessageDesc => "复制消息内容",
        MessageId::CtxMenuOpenInEditor => "在编辑器中打开",
        MessageId::CtxMenuOpenInEditorDesc => "在编辑器中打开",
        MessageId::CtxMenuShowCell => "显示单元格",
        MessageId::CtxMenuShowCellDesc => "显示单元格",
        MessageId::CtxMenuHideCell => "隐藏单元格",
        MessageId::CtxMenuHideCellDesc => "隐藏单元格",
        MessageId::CtxMenuShowHidden => "显示隐藏",
        MessageId::CtxMenuShowHiddenDesc => "显示隐藏内容",
        MessageId::CtxMenuPaste => "粘贴",
        MessageId::CtxMenuPasteDesc => "粘贴内容",
        MessageId::CtxMenuCmdPalette => "命令面板",
        MessageId::CtxMenuCmdPaletteDesc => "打开命令面板",
        MessageId::CtxMenuContextInspector => "上下文检查器",
        MessageId::CtxMenuContextInspectorDesc => "打开上下文检查器",
        MessageId::CtxMenuHelp => "帮助",
        MessageId::CtxMenuHelpDesc => "打开帮助",
        MessageId::FanoutCounts => "扇出计数",
        MessageId::ModePickerPrompt => "选择模式",
        MessageId::AppModeAgent => "代理",
        MessageId::AppModeYolo => "Yolo",
        MessageId::AppModePlan => "计划",
        MessageId::AppModeAgentHint => "代理模式提示",
        MessageId::AppModePlanHint => "计划模式提示",
        MessageId::AppModeYoloHint => "Yolo 模式提示",
        MessageId::VimModeNormal => "普通模式",
        MessageId::VimModeInsert => "插入模式",
        MessageId::VimModeVisual => "可视模式",
        MessageId::ApprovalRiskReview => "审查",
        MessageId::ApprovalRiskDestructive => "破坏性",
        MessageId::ApprovalCategorySafe => "安全",
        MessageId::ApprovalCategoryFileWrite => "文件写入",
        MessageId::ApprovalCategoryShell => "Shell",
        MessageId::ApprovalCategoryNetwork => "网络",
        MessageId::ApprovalCategoryMcpRead => "MCP 读取",
        MessageId::ApprovalCategoryMcpAction => "MCP 操作",
        MessageId::ApprovalCategoryUnknown => "未知",
        MessageId::ApprovalFieldType => "类型",
        MessageId::ApprovalFieldAbout => "关于",
        MessageId::ApprovalFieldImpact => "影响",
        MessageId::ApprovalFieldParams => "参数",
        MessageId::ApprovalOptionApproveOnce => "批准一次",
        MessageId::ApprovalOptionApproveAlways => "始终批准",
        MessageId::ApprovalOptionDeny => "拒绝",
        MessageId::ApprovalOptionAbortTurn => "中止",
        MessageId::ApprovalBlockTitle => "审批块",
        MessageId::ApprovalControlsHint => "控制提示",
        MessageId::ApprovalChooseHint => "选择提示",
        MessageId::ApprovalChooseAction => "选择操作",
        MessageId::ApprovalIntentLabel => "意图",
        MessageId::ApprovalMoreLines => "更多行",
        MessageId::ElevationTitleSandboxDenied => "沙箱拒绝",
        MessageId::ElevationTitleRequired => "需要提升",
        MessageId::ElevationFieldTool => "工具",
        MessageId::ElevationFieldCmd => "命令",
        MessageId::ElevationFieldReason => "原因",
        MessageId::ElevationImpactHeader => "影响",
        MessageId::ElevationImpactNetwork => "网络",
        MessageId::ElevationImpactWrite => "写入",
        MessageId::ElevationImpactFullAccess => "完全访问",
        MessageId::ElevationPromptProceed => "继续",
        MessageId::ElevationOptionNetwork => "网络",
        MessageId::ElevationOptionWrite => "写入",
        MessageId::ElevationOptionFullAccess => "完全访问",
        MessageId::ElevationOptionAbort => "中止",
        MessageId::ElevationOptionNetworkDesc => "网络描述",
        MessageId::ElevationOptionWriteDesc => "写入描述",
        MessageId::ElevationOptionFullAccessDesc => "完全访问描述",
        MessageId::ElevationOptionAbortDesc => "中止描述",
        MessageId::CtxInspTitle => "上下文检查器",
        MessageId::CtxInspSessionContext => "会话上下文",
        MessageId::CtxInspSystemPrompt => "系统提示",
        MessageId::CtxInspReferences => "引用",
        MessageId::CtxInspRecentTools => "最近工具",
        MessageId::CtxInspModel => "模型",
        MessageId::CtxInspWorkspace => "工作区",
        MessageId::CtxInspSession => "会话",
        MessageId::CtxInspContext => "上下文",
        MessageId::CtxInspTranscript => "转录",
        MessageId::CtxInspWorkspaceStatus => "工作区状态",
        MessageId::CtxInspNotSampledYet => "未采样",
        MessageId::CtxInspOk => "正常",
        MessageId::CtxInspHigh => "高",
        MessageId::CtxInspCritical => "严重",
        MessageId::CtxInspIncluded => "已包含",
        MessageId::CtxInspAttached => "已附加",
        MessageId::CtxInspNotIncluded => "未包含",
        MessageId::CtxInspOutputCaptured => "输出已捕获",
        MessageId::CtxInspNoOutputYet => "无输出",
        MessageId::CtxInspNoSystemPrompt => "无系统提示",
        MessageId::CtxInspNoReferences => "无引用",
        MessageId::CtxInspNoToolActivity => "无工具活动",
        MessageId::CtxInspVHint => "V 提示",
        MessageId::CtxInspCells => "单元格",
        MessageId::CtxInspApiMessages => "API 消息",
        MessageId::CtxInspActive => "活跃",
        MessageId::CtxInspCell => "单元格",
        MessageId::CtxInspMoreReferences => "更多引用",
        MessageId::CtxInspStablePrefix => "稳定前缀",
        MessageId::CtxInspVolatileWorkingSet => "易失工作集",
        MessageId::CtxInspFirstLine => "第一行",
        MessageId::CtxInspTotal => "总计",
        MessageId::CtxInspTextPromptLayers => "文本提示层",
        MessageId::CtxInspSingleTextBlob => "单文本块",
        MessageId::CtxInspBlocks => "块",
        MessageId::CtxInspBlock => "块",
        MessageId::CtxInspTokens => "Token",
        MessageId::CtxInspLayers => "层",
        MessageId::CtxInspNone => "无",
        MessageId::CtxInspEmpty => "空",
        MessageId::CtxInspCacheFriendly => "缓存友好",
        MessageId::CtxInspChangesByTurn => "按轮次变化",
        MessageId::CtxInspStablePrefixOnly => "仅稳定前缀",
        MessageId::CtxInspCacheTip => "缓存提示",
        MessageId::ToolFamilyRead => "读取",
        MessageId::ToolFamilyPatch => "补丁",
        MessageId::ToolFamilyRun => "运行",
        MessageId::ToolFamilyFind => "查找",
        MessageId::ToolFamilyDelegate => "委托",
        MessageId::ToolFamilyFanout => "扇出",
        MessageId::ToolFamilyRlm => "RLM",
        MessageId::ToolFamilyVerify => "验证",
        MessageId::ToolFamilyThink => "思考",
        MessageId::ToolFamilyGeneric => "通用",
        MessageId::CmdVoiceDescription => "语音输入",
        MessageId::CmdVoiceSendDescription => "语音发送",
        MessageId::CmdVoiceControlDescription => "语音控制",
        MessageId::VoiceEnabled => "语音已启用",
        MessageId::VoiceDisabled => "语音已禁用",
        MessageId::VoiceSendEnabled => "语音发送已启用",
        MessageId::VoiceSendDisabled => "语音发送已禁用",
        MessageId::VoiceControlEnabled => "语音控制已启用",
        MessageId::VoiceControlDisabled => "语音控制已禁用",
        MessageId::VoiceErrNoAuth => "无认证",
        MessageId::VoiceErrNoRecorder => "无录音器",
        MessageId::VoiceErrNetwork => "网络错误",
        MessageId::VoiceErrEmptySend => "空发送",
        MessageId::VoiceErrTooShort => "太短",
        MessageId::VoiceRecording => "录音中...",
        MessageId::VoiceProcessing => "处理中...",
        MessageId::VoiceTranscribed => "已转录",
    })
}

#[cfg(test)]
mod tests {}
