// AUTO-GENERATED by web/scripts/derive-facts.mjs at prebuild.
// DO NOT EDIT — re-run `pnpm prebuild` (or just `pnpm build`) after changing the parent repo.
// To override at runtime, write the same shape to KV under key "facts:current".

export interface ProviderFact { id: string; label: string; env: string }

export interface RepoFacts {
  generatedAt: string;
  version: string | null;
  crates: string[];
  sandboxBackends: string[];
  providers: ProviderFact[];
  defaultModel: string | null;
  nodeEngines: string | null;
  toolCount: number | null;
  license: string | null;
  latestRelease: string | null;
}

export const FACTS: RepoFacts = {
  "generatedAt": "2026-07-01T02:07:18.095Z",
  "version": "0.0.2",
  "crates": [
    "agent",
    "app-server",
    "cli",
    "config",
    "core",
    "execpolicy",
    "hooks",
    "mcp",
    "protocol",
    "release",
    "secrets",
    "state",
    "tools",
    "tui",
    "whaleflow"
  ],
  "sandboxBackends": [
    "bwrap",
    "landlock (Linux)",
    "process_hardening",
    "seatbelt (macOS)",
    "seccomp"
  ],
  "providers": [
    {
      "id": "xiaomi-mimo",
      "label": "Xiaomi MiMo",
      "env": "XIAOMI_MIMO_API_KEY / XIAOMI_API_KEY / MIMO_API_KEY"
    }
  ],
  "defaultModel": "deepseek-v4-pro",
  "nodeEngines": ">=18",
  "toolCount": 78,
  "license": "MIT",
  "latestRelease": null
};
